function createfigure(ZData1, YData1, XData1, CData1)
%CREATEFIGURE(ZDATA1, YDATA1, XDATA1, CDATA1)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 13-Jul-2020 15:17:09

% Create figure
figure1 = figure;
colormap(gray(256));

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surface
surface('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'AlignVertexCenters','on',...
    'FaceColor','interp',...
    'EdgeColor','none',...
    'CData',CData1);

% Create xlabel
xlabel('Azimuth [mm]');

% Create ylabel
ylabel('Depth [mm]');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.840893817204301 98.4492607526882]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'CLim',[-40 0],'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',...
    [62.4115967961827 49.2246303763441 1]);
